version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Prepare yourselves for the greatest battle of your life...
  build:
    commands:
      - echo Build started on date
  post_build:
    commands:
      - echo Build completed on date
artifacts:
  files:
    - tiango.yaml
